#! /bin/bash
#set -x
#cp $BUILDROOT/output/images/rootfs.cpio                  .
#cp $CONDOR_TOP/linux-5.8-rc4/arch/riscv/boot/Image       .
#cp $OPENSBI/build/platform/generic/firmware/fw_jump.bin  .
#cp $CONDOR_TOP/how-to/patches/cpm.boot.cfg               .
#
#JEFF_BM=/data/users/jeffnye/condor/benchmarks
#cp $JEFF_BM/bin/bmi_median.bare.riscv .
#cp $JEFF_BM/report/bmi_median.bare.riscv.dump .
#cp $JEFF_BM/bin/bmi_median.linux.riscv .
#cp $JEFF_BM/report/bmi_median.linux.riscv.dump .
#
#cp $JEFF_BM/bin/bmi_sanity.bare.riscv .
#cp $JEFF_BM/report/bmi_sanity.bare.riscv.dump .
#cp $JEFF_BM/bin/bmi_sanity.llvm.bare.riscv .
#cp $JEFF_BM/report/bmi_sanity.llvm.bare.riscv.dump .
#cp $JEFF_BM/bin/bmi_sanity.linux.riscv .
#cp $JEFF_BM/report/bmi_sanity.linux.riscv.dump .
#cp $JEFF_BM/bin/bmi_sanity.llvm.linux.riscv .
#cp $JEFF_BM/report/bmi_sanity.llvm.linux.riscv.dump .

#REMOTE=$CONDOR_TOP/cpm.dromajo.head
TEST=bmi_sanity.bare.riscv
##TEST=bmi_median.bare.riscv

rm -f bare.example.*stf
./dromajo \
--ctrlc \
--stf_priv_modes USHM \
--stf_include_tracepoints \
--stf_trace=bare.example.stf \
$TEST


#rm -f linux.example.*stf
#./dromajo \
#--ctrlc \
#--stf_priv_modes USHM \
#--stf_trace=linux.example.stf \
#cpm.boot.cfg

#echo "TRY DIFF -C"
#$CONDOR_TOP/stf_tools/release/tools/stf_diff/stf_diff -C bare.example.stf \
#$REMOTE/build/bare.example.stf
#
#echo "TRY DIFF MpRS"
#$CONDOR_TOP/stf_tools/release/tools/stf_diff/stf_diff -MpRS bare.example.stf \
#$REMOTE/build/bare.example.stf
#
#echo "TRY DIFF U"
#$CONDOR_TOP/stf_tools/release/tools/stf_diff/stf_diff -u bare.example.stf \
#$REMOTE/build/bare.example.stf
#
#echo "TRY INFO A -d"
#$CONDOR_TOP/stf_tools/release/tools/stf_trace_info/stf_trace_info -d \
#bare.example.stf 
#
#echo "TRY INFO B -d"
#$CONDOR_TOP/stf_tools/release/tools/stf_trace_info/stf_trace_info -d \
#$REMOTE/build/bare.example.stf
#
echo "TRY DUMP 1 -p"
$CONDOR_TOP/stf_tools/release/tools/stf_record_dump/stf_record_dump -p \
bare.example.stf > dump1

#echo "TRY DUMP 2 -p"
#$CONDOR_TOP/stf_tools/release/tools/stf_record_dump/stf_record_dump -p \
#$REMOTE/build/bare.example.stf > dump2

#echo "TRY DIFF"
#diff dump1 dump2
#
#echo "TRY COUNT 1 "
#$CONDOR_TOP/stf_tools/release/tools/stf_count/stf_count -v bare.example.stf 
#
#echo "TRY LS -LH"
#ls -lh bare.example.stf 
#ls -lh $REMOTE/build/bare.example.stf
#ls -lh linux.example.stf 
#ls -lh $REMOTE/build/linux.example.stf

